version: 2

sphinx:
  builder: html
  configuration: doc/conf.py

formats: all

build:
  os: ubuntu-22.04
  apt_packages:
    - libopenmpi-dev
  tools:
    python: "3.10"

python:
  install:
    - method: pip
      path: .[docs,jupyter]
