version: 2

sphinx:
  builder: html
  configuration: doc/conf.py

formats: all

build:
  os: ubuntu-22.04
  apt_packages:
    - libopenmpi-dev

python:
  version: "3.10"
  install:
    - method: pip
      path: .[docs,jupyter]
